# Site Wild Settings
# ------------------
title: 佛法藏
#
# author:
#   name: GitHub User
#   email: your-email@domain.com
#
description: >
    佛法藏

# Build settings
# --------------
theme: minima

plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-sitemap

sass:
    quiet_deps: true
    silence_deprecations: [import]
    style: compressed

# Minima-specific settings (applicable to Minima v3 and above only)
# -----------------------------------------------------------------
minima:
    skin: classic
    date_format: "%Y/%m/%d"
    nav_pages:
       - about.md
    show_excerpts: false

permalink: /:title:output_ext

timezone: Asia/Shanghai